linter:
  # Manually specifying some lint rules for the moment as the analysis server
  # seems to be unable to handle includes at this time.
  rules:
    - public_member_api_docs
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - sort_child_properties_last
    - sort_constructors_first
    - unnecessary_const
    - unnecessary_brace_in_string_interps
